name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Verify distribution files
      run: |
        echo "Listing files in dist directory:"
        ls -l dist/

    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pip install pytest
        pytest

    - name: Publish package to PyPI
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        python -m pip install twine
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish package to GitHub Packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        python -m pip install twine
        twine upload --repository-url https://upload.github.com/${{ github.repository }}/dist/*
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
